on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        default: 'World'
        required: true
        type: string

    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Greet everyone
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

    outputs:
      current-time: ${{ steps.time.outputs.time }}

    
